#pragma once

typedef enum ACCEL_MODE
{
    ACCEL_MODE_OFF = 0,
    _ACCEL_MODE_OFF_2,
    ACCEL_MODE_LP,
    ACCEL_MODE_LN,
} __ICM45686_ACCEL_MODE_t;

typedef enum GYRO_MODE
{
    GYRO_MODE_OFF = 0,
    _GYRO_MODE_OFF_2,
    GYRO_MODE_LP,
    GYRO_MODE_LN,
} __ICM45686_GYRO_MODE_t;

typedef enum INT_POLARITY
{
    INT_POLARITY_ACTIVE_LOW = 0,
    INT_POLARITY_ACTIVE_HIGH,
} __ICM45686_INT_POLARITY_t;

typedef enum INT_MODE
{
    INT_MODE_PULSE = 0,
    INT_MODE_LATCH,
} __ICM45686_INT_MODE_t;

typedef enum INT_DRIVE
{
    INT_DRIVE_PUSH_PULL = 0,
    INT_DRIVE_OPEN_DRAIN,
} __ICM45686_INT_DRIVE_t;

typedef enum ACCEL_UI_FS_SEL
{
    ACCEL_UI_SCALE_32G = 0,
    ACCEL_UI_SCALE_16G,
    ACCEL_UI_SCALE_8G,
    ACCEL_UI_SCALE_4G,
    ACCEL_UI_SCALE_2G,
    _ACCEL_UI_SCALE_RES1,
    _ACCEL_UI_SCALE_RES2,
    _ACCEL_UI_SCALE_RES3,
} __ICM45686_ACCEL_UI_FS_SEL_t;

typedef enum ACCEL_ODR
{
    _ACCEL_ODR_RES1 = 0,
    _ACCEL_ODR_RES2,
    _ACCEL_ODR_RES3,
    ACCEL_ODR_6400HZ,
    ACCEL_ODR_3200HZ,
    ACCEL_ODR_1600HZ,
    ACCEL_ODR_800HZ,
    ACCEL_ODR_400HZ,
    ACCEL_ODR_200HZ,
    ACCEL_ODR_100HZ,
    ACCEL_ODR_50HZ,
    ACCEL_ODR_25HZ,
    ACCEL_ODR_12P5HZ,
    ACCEL_ODR_6P25HZ,
    ACCEL_ODR_3P125HZ,
    ACCEL_ODR_1P5625HZ,
} __ICM45686_ACCEL_ODR_t;

typedef enum GYRO_UI_FS_SEL
{
    GYRO_UI_SCALE_4000DPS = 0,
    GYRO_UI_SCALE_2000DPS,
    GYRO_UI_SCALE_1000DPS,
    GYRO_UI_SCALE_500DPS,
    GYRO_UI_SCALE_250DPS,
    GYRO_UI_SCALE_125DPS,
    GYRO_UI_SCALE_62P5DPS,
    GYRO_UI_SCALE_31P25DPS,
    GYRO_UI_SCALE_15P625DPS,
    _GYRO_UI_SCALE_RES1,
    _GYRO_UI_SCALE_RES2,
    _GYRO_UI_SCALE_RES3,
    _GYRO_UI_SCALE_RES4,
    _GYRO_UI_SCALE_RES5,
    _GYRO_UI_SCALE_RES6,
    _GYRO_UI_SCALE_RES7,
} __ICM45686_GYRO_UI_FS_SEL_t;

typedef enum GYRO_ODR
{
    _GYRO_ODR_RES1 = 0,
    _GYRO_ODR_RES2,
    _GYRO_ODR_RES3,
    GYRO_ODR_6400HZ,
    GYRO_ODR_3200HZ,
    GYRO_ODR_1600HZ,
    GYRO_ODR_800HZ,
    GYRO_ODR_400HZ,
    GYRO_ODR_200HZ,
    GYRO_ODR_100HZ,
    GYRO_ODR_50HZ,
    GYRO_ODR_25HZ,
    GYRO_ODR_12P5HZ,
    GYRO_ODR_6P25HZ,
    GYRO_ODR_3P125HZ,
    GYRO_ODR_1P5625HZ,
} __ICM45686_GYRO_ODR_t;

typedef enum FIFO_MODE
{
    FIFO_MODE_BYPASS = 0,
    FIFO_MODE_STREAM,
    FIFO_MODE_STOP_ON_FULL,
    _FIFO_MODE_RESERVED,
} __ICM45686_FIFO_MODE_t;

typedef enum FIFO_DEPTH
{
    FIFO_DEPTH_2K = 0b000111,
    FIFO_DEPTH_8K = 0b011111,
} __ICM45686_FIFO_DEPTH_t;

typedef enum FIFO_WR_WM_GT_TH
{
    FIFO_WM_INT_IF_EQUAL = 0,
    FIFO_WM_INT_IF_GREATER_OR_EQUAL = 1,
} __ICM45686_FIFO_WR_WM_GT_TH_t;

typedef enum FIFO_ES0_6B_9B
{
    FIFO_ES0_6_BYTES = 0,
    FIFO_ES0_9_BYTES = 1,
} __ICM45686_FIFO_ES0_6B_9B_t;

typedef enum FIFO_COMP_NC_FLOW_CFG
{
    NON_COMPRESSED_PACKET_FLOW_DIS = 0,
    NON_COMPRESSED_PACKET_EVERY_8_FRAMES,
    NON_COMPRESSED_PACKET_EVERY_16_FRAMES,
    NON_COMPRESSED_PACKET_EVERY_32_FRAMES,
    NON_COMPRESSED_PACKET_EVERY_64_FRAMES,
    NON_COMPRESSED_PACKET_EVERY_128_FRAMES,
    _NON_COMPRESSED_PACKET_RES1,
    _NON_COMPRESSED_PACKET_RES2,
} __ICM45686_FIFO_COMP_NC_FLOW_CFG_t;

typedef enum WOM_INT_DUR
{
    WOM_INT_DUR_FIRST_OVER_THS_EVNT = 0,
    WOM_INT_DUR_SECOND_OVER_THS_EVNT,
    WOM_INT_DUR_THIRD_OVER_THS_EVNT,
    WOM_INT_DUR_FOURTH_OVER_THS_EVNT,
} __ICM45686_WOM_INT_DUR_t;

typedef enum WOM_MODE
{
    WOM_MODE_INITIAL_SAMPLE_IS_STORED = 0,
    WOM_MODE_COMPARE_CUR_TO_PREV,
} __ICM45686_WOM_MODE_t;

typedef enum TMST_RESOL
{
    TMST_RESOL_1US = 0,
    TMST_RESOL_16US,
} __ICM45686_TMST_RESOL;

typedef enum AP_FSYNC_SEL
{
    APUI_FSYNC_TAG_DISABLED = 0,
    APUI_FSYNC_TAG_TO_TEMP_DATA_UI_LSB,
    APUI_FSYNC_TAG_TO_GYRO_DATA_X_UI_LSB,
    APUI_FSYNC_TAG_TO_GYRO_DATA_Y_UI_LSB,
    APUI_FSYNC_TAG_TO_GYRO_DATA_Z_UI_LSB,
    APUI_FSYNC_TAG_TO_ACCEL_DATA_X_UI_LSB,
    APUI_FSYNC_TAG_TO_ACCEL_DATA_Y_UI_LSB,
    APUI_FSYNC_TAG_TO_ACCEL_DATA_Z_UI_LSB,
} __ICM45686_AP_FSYNC_SEL_t;

typedef enum AP_FSYNC_FLAG_CLEAR_SEL
{
    APUI_FSYNC_CLEAR_ON_REGISTER_UPDATE = 0,
    APUI_FSYNC_CLEAR_ON_REGISTER_READ,
} __ICM45686_AP_FSYNC_FLAG_CLEAR_SEL_t;

typedef enum AUX1_FSYNC_SEL
{
    AUX1_FSYNC_TAG_DISABLED = 0,
    AUX1_FSYNC_TAG_TO_TEMP_DATA_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_GYRO_DATA_X_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_GYRO_DATA_Y_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_GYRO_DATA_Z_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_ACCEL_DATA_X_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_ACCEL_DATA_Y_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_ACCEL_DATA_Z_AUX1_LSB,
} __ICM45686_AUX1_FSYNC_SEL_t;

typedef enum AUX1_FSYNC_FLAG_CLEAR_SEL
{
    AUX1_FSYNC_CLEAR_ON_REGISTER_UPDATE = 0,
    AUX1_FSYNC_CLEAR_ON_REGISTER_READ,
} __ICM45686_AUX1_FSYNC_FLAG_CLEAR_SEL_t;

typedef enum APEX_ODR
{
    APEX_ODR_25HZ = 0,
    APEX_ODR_50HZ,
    APEX_ODR_100HZ,
    APEX_ODR_200HZ,
    APEX_ODR_400HZ,
    APEX_ODR_800HZ,
    _APEX_ODR_RES1,
    _APEX_ODR_RES2,
} __ICM45686_APEX_ODR_t;

typedef enum I2CM_EXT_ODR
{
    I2CM_EXT_ODR_3P125HZ = 0,
    I2CM_EXT_ODR_6P25HZ,
    I2CM_EXT_ODR_12P5HZ,
    I2CM_EXT_ODR_25HZ,
    I2CM_EXT_ODR_50HZ,
    I2CM_EXT_ODR_100HZ,
    I2CM_EXT_ODR_200HZ,
    I2CM_EXT_ODR_400HZ,
} __ICM45686_I2CM_EXT_ODR_t;

typedef enum ACCEL_FIFO_ODR_DEC
{
    ACCEL_FIFO_ODR_DEC_1 = 0,
    ACCEL_FIFO_ODR_DEC_2,
    ACCEL_FIFO_ODR_DEC_4,
    ACCEL_FIFO_ODR_DEC_8,
    ACCEL_FIFO_ODR_DEC_16,
    ACCEL_FIFO_ODR_DEC_32,
    ACCEL_FIFO_ODR_DEC_64,
    ACCEL_FIFO_ODR_DEC_128,
    ACCEL_FIFO_ODR_DEC_256,
    ACCEL_FIFO_ODR_DEC_512,
    ACCEL_FIFO_ODR_DEC_1024,
    ACCEL_FIFO_ODR_DEC_2048,
    ACCEL_FIFO_ODR_DEC_4096,
    _ACCEL_FIFO_ODR_DEC_RES1,
    _ACCEL_FIFO_ODR_DEC_RES2,
    _ACCEL_FIFO_ODR_DEC_RES3,
} __ICM45686_ACCEL_FIFO_ODR_DEC_t;

typedef enum GYRO_FIFO_ODR_DEC
{
    GYRO_FIFO_ODR_DEC_1 = 0,
    GYRO_FIFO_ODR_DEC_2,
    GYRO_FIFO_ODR_DEC_4,
    GYRO_FIFO_ODR_DEC_8,
    GYRO_FIFO_ODR_DEC_16,
    GYRO_FIFO_ODR_DEC_32,
    GYRO_FIFO_ODR_DEC_64,
    GYRO_FIFO_ODR_DEC_128,
    GYRO_FIFO_ODR_DEC_256,
    GYRO_FIFO_ODR_DEC_512,
    GYRO_FIFO_ODR_DEC_1024,
    GYRO_FIFO_ODR_DEC_2048,
    GYRO_FIFO_ODR_DEC_4096,
    _GYRO_FIFO_ODR_DEC_RES1,
    _GYRO_FIFO_ODR_DEC_RES2,
    _GYRO_FIFO_ODR_DEC_RES3,
} __ICM45686_GYRO_FIFO_ODR_DEC_t;

typedef enum AP_SPI_MODE
{
    AP_SPI_MODE_0_3 = 0,
    AP_SPI_MODE_1_2,
} __ICM45686_AP_SPI_MODE_t;

typedef enum AP_SPI_34_MODE
{
    AP_SPI_34_MODE_3WIRE = 0,
    AP_SPI_34_MODE_4WIRE,
} __ICM45686_AP_SPI_34_MODE_t;

typedef enum AP_SPI_MODE_OVRD_VAL
{
    AP_SPI_MODE_OVRD_VAL_0_3 = 0,
    AP_SPI_MODE_OVRD_VAL_1_2,
} __ICM45686_AP_SPI_MODE_OVRD_VAL_t;

typedef enum AP_SPI_34_MODE_OVRD_VAL
{
    AP_SPI_34_MODE_OVRD_VAL_3WIRE = 0,
    AP_SPI_34_MODE_OVRD_VAL_4WIRE,
} __ICM45686_AP_SPI_34_MODE_OVRD_VAL_t;

typedef enum AUX1_SPI_MODE
{
    AUX1_SPI_MODE_0_3 = 0,
    AUX1_SPI_MODE_1_2,
} __ICM45686_AUX1_SPI_MODE_t;

typedef enum AUX1_SPI_34_MODE
{
    AUX1_SPI_34_MODE_3WIRE = 0,
    AUX1_SPI_34_MODE_4WIRE,
} __ICM45686_AUX1_SPI_34_MODE_t;

typedef enum AUX1_MODE
{
    AUX1_MODE_SPI_SLAVE = 0,
    AUX1_MODE_I2C_MASTER,
    AUX1_MODE_I2C_BYPASS,
    _AUX1_MODE_RESERVED,
} __ICM45686_AUX1_MODE_t;

typedef enum AUX1_MODE_OVRD_VAL
{
    AUX1_MODE_OVRD_VAL_SPI_SLAVE = 0,
    AUX1_MODE_OVRD_VAL_I2C_MASTER,
    AUX1_MODE_OVRD_VAL_I2C_BYPASS,
    _AUX1_MODE_OVRD_VAL_RESERVED,
} __ICM45686_AUX1_MODE_OVRD_VAL_t;

typedef enum PADS_SPI_SLEW
{
    PADS_SPI_SLEW_38NS = 0,
    PADS_SPI_SLEW_14NS,
    PADS_SPI_SLEW_10NS,
    PADS_SPI_SLEW_7NS,
    PADS_SPI_SLEW_5NS,
    PADS_SPI_SLEW_4NS,
    PADS_SPI_SLEW_0P5NS,
    _PADS_SPI_SLEW_0P5NS_2,
} __ICM45686_PADS_SPI_SLEW_t;

typedef enum PADS_I2C_SLEW
{
    PADS_I2C_SLEW_20NS = 0,
    _PADS_I2C_SLEW_RES1,
    PADS_I2C_SLEW_7NS,
    _PADS_I2C_SLEW_RES2,
    _PADS_I2C_SLEW_RES3,
    _PADS_I2C_SLEW_RES4,
    _PADS_I2C_SLEW_RES5,
    _PADS_I2C_SLEW_RES6,
} __ICM45686_PADS_I2C_SLEW_t;

typedef enum PADS_I3C_SDR_SLEW
{
    PADS_I3C_SDR_SLEW_38NS = 0,
    PADS_I3C_SDR_SLEW_14NS,
    PADS_I3C_SDR_SLEW_10NS,
    PADS_I3C_SDR_SLEW_7NS,
    PADS_I3C_SDR_SLEW_5NS,
    PADS_I3C_SDR_SLEW_4NS,
    PADS_I3C_SDR_SLEW_0P5NS,
    _PADS_I3C_SDR_SLEW_0P5NS_2,
} __ICM45686_PADS_I3C_SDR_SLEW_t;

typedef enum PADS_I3C_DDR_SLEW
{
    PADS_I3C_DDR_SLEW_38NS = 0,
    PADS_I3C_DDR_SLEW_14NS,
    PADS_I3C_DDR_SLEW_10NS,
    PADS_I3C_DDR_SLEW_7NS,
    PADS_I3C_DDR_SLEW_5NS,
    PADS_I3C_DDR_SLEW_4NS,
    PADS_I3C_DDR_SLEW_0P5NS,
    _PADS_I3C_DDR_SLEW_0P5NS_2,
} __ICM45686_PADS_I3C_DDR_SLEW_t;

typedef enum PADS_SLEW
{
    PADS_INT1_SLEW_38NS = 0,
    PADS_INT1_SLEW_14NS,
    PADS_INT1_SLEW_10NS,
    PADS_INT1_SLEW_7NS,
    PADS_INT1_SLEW_5NS,
    PADS_INT1_SLEW_4NS,
    PADS_INT1_SLEW_0P5NS,
    _PADS_INT1_SLEW_0P5NS_2,
} __ICM45686_PADS_SLEW_t;

typedef enum OSC_ID_OVRD
{
    MCLK_SOURCE_INTERNAL_LOGIC = 0b0000,
    _MCLK_SOURCE_RES1,
    MCLK_SOURCE_INTERNAL_OSCILLATOR = 0b0010,
    _MCLK_SOURCE_RES2,
    _MCLK_SOURCE_RES3,
    _MCLK_SOURCE_RES4,
    _MCLK_SOURCE_RES5,
    _MCLK_SOURCE_RES6,
    MCLK_SOURCE_EXTERNAL_CLOCK = 0b1000,
    _MCLK_SOURCE_RES7,
    _MCLK_SOURCE_RES8,
    _MCLK_SOURCE_RES9,
    _MCLK_SOURCE_RES10,
    _MCLK_SOURCE_RES11,
    _MCLK_SOURCE_RES12,
    _MCLK_SOURCE_RES13,
} __ICM45686_OSC_ID_OVRD_t;

typedef enum ACCEL_AUX1_FS_SEL
{
    ACCEL_AUX1_SCALE_32G = 0,
    ACCEL_AUX1_SCALE_16G,
    ACCEL_AUX1_SCALE_8G,
    ACCEL_AUX1_SCALE_4G,
    ACCEL_AUX1_SCALE_2G,
    _ACCEL_AUX1_SCALE_RES1,
    _ACCEL_AUX1_SCALE_RES2,
    _ACCEL_AUX1_SCALE_RES3,
} __ICM45686_ACCEL_AUX1_FS_SEL_t;

typedef enum GYRO_AUX1_FS_SEL
{
    GYRO_AUX1_SCALE_4000DPS = 0,
    GYRO_AUX1_SCALE_2000DPS,
    GYRO_AUX1_SCALE_1000DPS,
    GYRO_AUX1_SCALE_500DPS,
    GYRO_AUX1_SCALE_250DPS,
    GYRO_AUX1_SCALE_125DPS,
    GYRO_AUX1_SCALE_62P5DPS,
    GYRO_AUX1_SCALE_31P25DPS,
    GYRO_AUX1_SCALE_15P625DPS,
    _GYRO_AUX1_SCALE_RES1,
    _GYRO_AUX1_SCALE_RES2,
    _GYRO_AUX1_SCALE_RES3,
    _GYRO_AUX1_SCALE_RES4,
    _GYRO_AUX1_SCALE_RES5,
    _GYRO_AUX1_SCALE_RES6,
    _GYRO_AUX1_SCALE_RES7,
} __ICM45686_GYRO_AUX1_FS_SEL_t;