#pragma once

typedef enum ACCEL_MODE
{
    ACCEL_MODE_OFF = 0b00,
    ACCEL_MODE_OFF_2 = 0b01,
    ACCEL_MODE_LP = 0b10,
    ACCEL_MODE_LN = 0b11,
};

typedef enum GYRO_MODE
{
    GYRO_MODE_OFF = 0b00,
    GYRO_MODE_OFF_2 = 0b01,
    GYRO_MODE_LP = 0b10,
    GYRO_MODE_LN = 0b11,
};

typedef enum INT_POLARITY
{
    INT_POLARITY_ACTIVE_HIGH = 1,
    INT_POLARITY_ACTIVE_LOW = 0,
};

typedef enum INT_MODE
{
    INT_MODE_PULSE = 0,
    INT_MODE_LATCH = 1,
};

typedef enum INT_DRIVE
{
    INT_DRIVE_PUSH_PULL = 0,
    INT_DRIVE_OPEN_DRAIN = 1,
};

typedef enum ACCEL_UI_FS_SEL
{
    ACCEL_SCALE_32G = 0b000,
    ACCEL_SCALE_16G = 0b001,
    ACCEL_SCALE_8G = 0b010,
    ACCEL_SCALE_4G = 0b011,
    ACCEL_SCALE_2G = 0b100,
    ACCEL_SCALE_RES1 = 0b101,
    ACCEL_SCALE_RES2 = 0b110,
    ACCEL_SCALE_RES3 = 0b111,
};

typedef enum ACCEL_ODR
{
    ACCEL_ODR_RES1 = 0b0000,
    ACCEL_ODR_RES2 = 0b0001,
    ACCEL_ODR_RES3 = 0b0010,
    ACCEL_ODR_6400HZ = 0b0011,
    ACCEL_ODR_3200HZ = 0b0100,
    ACCEL_ODR_1600HZ = 0b0101,
    ACCEL_ODR_800HZ = 0b0110,
    ACCEL_ODR_400HZ = 0b0111,
    ACCEL_ODR_200HZ = 0b1000,
    ACCEL_ODR_100HZ = 0b1001,
    ACCEL_ODR_50HZ = 0b1010,
    ACCEL_ODR_25HZ = 0b1011,
    ACCEL_ODR_12P5HZ = 0b1100,
    ACCEL_ODR_6P25HZ = 0b1101,
    ACCEL_ODR_3P125HZ = 0b1110,
    ACCEL_ODR_1P5625HZ = 0b1111,
};

typedef enum GYRO_UI_FS_SEL
{
    GYRO_SCALE_4000DPS = 0b0000,
    GYRO_SCALE_2000DPS = 0b0001,
    GYRO_SCALE_1000DPS = 0b0010,
    GYRO_SCALE_500DPS = 0b0011,
    GYRO_SCALE_250DPS = 0b0100,
    GYRO_SCALE_125DPS = 0b0101,
    GYRO_SCALE_62P5DPS = 0b0110,
    GYRO_SCALE_31P25DPS = 0b0111,
    GYRO_SCALE_15P625DPS = 0b1000,
    GYRO_SCALE_RES1,
    GYRO_SCALE_RES2,
    GYRO_SCALE_RES3,
    GYRO_SCALE_RES4,
    GYRO_SCALE_RES5,
    GYRO_SCALE_RES6,
    GYRO_SCALE_RES7,
};

typedef enum GYRO_ODR
{
    GYRO_ODR_RES1 = 0,
    GYRO_ODR_RES2,
    GYRO_ODR_RES3,
    GYRO_ODR_6400HZ,
    GYRO_ODR_3200HZ,
    GYRO_ODR_1600HZ,
    GYRO_ODR_800HZ,
    GYRO_ODR_400HZ,
    GYRO_ODR_200HZ,
    GYRO_ODR_100HZ,
    GYRO_ODR_50HZ,
    GYRO_ODR_25HZ,
    GYRO_ODR_12P5HZ,
    GYRO_ODR_6P25HZ,
    GYRO_ODR_3P125HZ,
    GYRO_ODR_1P5625HZ,
};

typedef enum FIFO_MODE
{
    FIFO_MODE_BYPASS = 0,
    FIFO_MODE_STREAM,
    FIFO_MODE_STOP_ON_FULL,
    FIFO_MODE_RESERVED,
};

typedef enum FIFO_DEPTH
{
    FIFO_DEPTH_2K = 0b000111,
    FIFO_DEPTH_8K = 0b011111,
};

typedef enum FIFO_WR_WM_GT_TH
{
    FIFO_WM_INT_IF_EQUAL = 0,
    FIFO_WM_INT_IF_GREATER_OR_EQUAL = 1,
};

typedef enum FIFO_ES0_6B_9B
{
    EXTERNAL_SENSOR0_6_BYTES = 0,
    EXTERNAL_SENSOR0_9_BYTES = 1,
};

typedef enum FIFO_COMP_NC_FLOW_CFG
{
    NON_COMPRESSED_PACKET_FLOW_DIS = 0,
    NON_COMPRESSED_PACKET_EVERY_8_FRAMES,
    NON_COMPRESSED_PACKET_EVERY_16_FRAMES,
    NON_COMPRESSED_PACKET_EVERY_32_FRAMES,
    NON_COMPRESSED_PACKET_EVERY_64_FRAMES,
    NON_COMPRESSED_PACKET_EVERY_128_FRAMES,
    NON_COMPRESSED_PACKET_RES1,
    NON_COMPRESSED_PACKET_RES2,
};

typedef enum WOM_INT_DUR
{
    WOM_INT_DUR_FIRST_OVER_THS_EVNT = 0,
    WOM_INT_DUR_SECOND_OVER_THS_EVNT,
    WOM_INT_DUR_THIRD_OVER_THS_EVNT,
    WOM_INT_DUR_FOURTH_OVER_THS_EVNT,
};

typedef enum WOM_MODE
{
    WOM_MODE_INITIAL_SAMPLE_IS_STORED = 0,
    WOM_MODE_COMPARE_CUR_TO_PREV,
};

typedef enum TMST_RESOL
{
    TMST_RESOL_1US = 0,
    TMST_RESOL_16US,
};

typedef enum AP_FSYNC_SEL
{
    APUI_FSYNC_TAG_DISABLED = 0,
    APUI_FSYNC_TAG_TO_TEMP_DATA_UI_LSB,
    APUI_FSYNC_TAG_TO_GYRO_DATA_X_UI_LSB,
    APUI_FSYNC_TAG_TO_GYRO_DATA_Y_UI_LSB,
    APUI_FSYNC_TAG_TO_GYRO_DATA_Z_UI_LSB,
    APUI_FSYNC_TAG_TO_ACCEL_DATA_X_UI_LSB,
    APUI_FSYNC_TAG_TO_ACCEL_DATA_Y_UI_LSB,
    APUI_FSYNC_TAG_TO_ACCEL_DATA_Z_UI_LSB,
};

typedef enum AP_FSYNC_FLAG_CLEAR_SEL
{
    APUI_FSYNC_CLEAR_ON_REGISTER_UPDATE = 0,
    APUI_FSYNC_CLEAR_ON_REGISTER_READ,
};

typedef enum AUX1_FSYNC_SEL
{
    AUX1_FSYNC_TAG_DISABLED = 0,
    AUX1_FSYNC_TAG_TO_TEMP_DATA_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_GYRO_DATA_X_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_GYRO_DATA_Y_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_GYRO_DATA_Z_AUX1_LSB,
    AUX1_SYNC_TAG_TO_ACCEL_DATA_X_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_ACCEL_DATA_Y_AUX1_LSB,
    AUX1_FSYNC_TAG_TO_ACCEL_DATA_Z_AUX1_LSB,
};

typedef enum AUX1_FSYNC_FLAG_CLEAR_SEL
{
    AUX1_FSYNC_CLEAR_ON_REGISTER_UPDATE = 0,
    AUX1_FSYNC_CLEAR_ON_REGISTER_READ,
};

typedef enum APEX_ODR
{
    APEX_ODR_25HZ = 0,
    APEX_ODR_50HZ,
    APEX_ODR_100HZ,
    APEX_ODR_200HZ,
    APEX_ODR_400HZ,
    APEX_ODR_800HZ,
    APEX_ODR_RES1,
    APEX_ODR_RES2,
};

typedef enum I2CM_EXT_ODR
{
    I2CM_EXT_ODR_3P125HZ = 0,
    I2CM_EXT_ODR_6P25HZ,
    I2CM_EXT_ODR_12P5HZ,
    I2CM_EXT_ODR_25HZ,
    I2CM_EXT_ODR_50HZ,
    I2CM_EXT_ODR_100HZ,
    I2CM_EXT_ODR_200HZ,
    I2CM_EXT_ODR_400HZ,
};

